title: NOTES by mike
domain: notes.mcgwiz.com
url: https://notes.mcgwiz.com/ # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
plugins:
  - jekyll-feed
disqus:
  shortname: notes-18
minima:
  skin: auto
permalink: /:slug
